WKLib: WKLib.API.Config.ConfigFolder Class Reference
WKLib.API.Config.ConfigFolder Class Reference
Public Member Functions
ConfigFolder (string folderName)
ConfigFolder (ConfigFolder parent, string folderName)
ConfigFolder GetSubFolder (string folderName)
ConfigFolder CreateSubFolder (string folderName)
ConfigFolder GetOrCreateSubFolder (string folderName)
bool RegisterConfigFolder (string folderName)
ConfigFile GetConfigFile (string fileName)
ConfigFile CreateConfigFile (string fileName)
ConfigFile GetOrCreateConfigFile (string fileName)
bool RegisterConfigFile (string fileName)
ConfigFolder LoadFiles ()
List< ConfigFolder > GetConfigFolders ()
List< ConfigFile > GetConfigFiles ()
IEnumerable< ConfigFile > EnumerateFiles ()
Properties
string BasePath [get]
string FolderName [get]
Detailed Description
Definition at line 9 of file ConfigFolder.cs.
Constructor & Destructor Documentation
ConfigFolder() [1/2]
WKLib.API.Config.ConfigFolder.ConfigFolder (string folderName)
Definition at line 18 of file ConfigFolder.cs.
References WKLib.API.Config.ConfigFolder.BasePath, WKLib.API.Config.ConfigFolder.FolderName, and WKLib.API.Config.ConfigFolder.LoadFiles().
Referenced by WKLib.API.Config.ConfigFolder.CreateSubFolder(), WKLib.API.Config.ConfigFolder.GetOrCreateSubFolder(), and WKLib.API.Config.ConfigFolder.RegisterConfigFolder().
ConfigFolder() [2/2]
WKLib.API.Config.ConfigFolder.ConfigFolder (ConfigFolder parent, string folderName)
Definition at line 34 of file ConfigFolder.cs.
References WKLib.API.Config.ConfigFolder.BasePath, WKLib.API.Config.ConfigFolder.FolderName, and WKLib.API.Config.ConfigFolder.LoadFiles().
Member Function Documentation
CreateConfigFile()
ConfigFile WKLib.API.Config.ConfigFolder.CreateConfigFile (string fileName)
Definition at line 143 of file ConfigFolder.cs.
CreateSubFolder()
ConfigFolder WKLib.API.Config.ConfigFolder.CreateSubFolder (string folderName)
Definition at line 68 of file ConfigFolder.cs.
References WKLib.API.Config.ConfigFolder.BasePath, and WKLib.API.Config.ConfigFolder.ConfigFolder().
EnumerateFiles()
IEnumerable< ConfigFile > WKLib.API.Config.ConfigFolder.EnumerateFiles ()
Definition at line 238 of file ConfigFolder.cs.
GetConfigFile()
ConfigFile WKLib.API.Config.ConfigFolder.GetConfigFile (string fileName)
Definition at line 127 of file ConfigFolder.cs.
GetConfigFiles()
List< ConfigFile > WKLib.API.Config.ConfigFolder.GetConfigFiles ()
Definition at line 231 of file ConfigFolder.cs.
GetConfigFolders()
List< ConfigFolder > WKLib.API.Config.ConfigFolder.GetConfigFolders ()
Definition at line 225 of file ConfigFolder.cs.
GetOrCreateConfigFile()
ConfigFile WKLib.API.Config.ConfigFolder.GetOrCreateConfigFile (string fileName)
Definition at line 161 of file ConfigFolder.cs.
GetOrCreateSubFolder()
ConfigFolder WKLib.API.Config.ConfigFolder.GetOrCreateSubFolder (string folderName)
Definition at line 87 of file ConfigFolder.cs.
References WKLib.API.Config.ConfigFolder.BasePath, and WKLib.API.Config.ConfigFolder.ConfigFolder().
GetSubFolder()
ConfigFolder WKLib.API.Config.ConfigFolder.GetSubFolder (string folderName)
Definition at line 52 of file ConfigFolder.cs.
LoadFiles()
ConfigFolder WKLib.API.Config.ConfigFolder.LoadFiles ()
Definition at line 201 of file ConfigFolder.cs.
References WKLib.API.Config.ConfigFolder.BasePath, WKLib.API.Config.ConfigFolder.RegisterConfigFile(), and WKLib.API.Config.ConfigFolder.RegisterConfigFolder().
Referenced by WKLib.API.Config.ConfigFolder.ConfigFolder(), and WKLib.API.Config.ConfigFolder.ConfigFolder().
RegisterConfigFile()
bool WKLib.API.Config.ConfigFolder.RegisterConfigFile (string fileName)
Definition at line 179 of file ConfigFolder.cs.
Referenced by WKLib.API.Config.ConfigFolder.LoadFiles().
RegisterConfigFolder()
bool WKLib.API.Config.ConfigFolder.RegisterConfigFolder (string folderName)
Definition at line 106 of file ConfigFolder.cs.
References WKLib.API.Config.ConfigFolder.BasePath, and WKLib.API.Config.ConfigFolder.ConfigFolder().
Referenced by WKLib.API.Config.ConfigFolder.LoadFiles().
Property Documentation
BasePath
string WKLib.API.Config.ConfigFolder.BasePath get
Definition at line 11 of file ConfigFolder.cs.
Referenced by WKLib.API.Config.ConfigFile.ConfigFile(), WKLib.API.Config.ConfigFolder.ConfigFolder(), WKLib.API.Config.ConfigFolder.ConfigFolder(), WKLib.API.Config.ConfigFolder.CreateSubFolder(), WKLib.API.Config.ConfigFolder.GetOrCreateSubFolder(), WKLib.API.Config.ConfigFolder.LoadFiles(), and WKLib.API.Config.ConfigFolder.RegisterConfigFolder().
FolderName
string WKLib.API.Config.ConfigFolder.FolderName get
Definition at line 12 of file ConfigFolder.cs.
Referenced by WKLib.API.Config.ConfigFolder.ConfigFolder(), and WKLib.API.Config.ConfigFolder.ConfigFolder().
The documentation for this class was generated from the following file:
API/Config/ConfigFolder.cs